version: '3.7'

services:
  wefox-proxy:
    image: nginx:alpine
    container_name: wefox-proxy
    ports:
      - '8080:8080'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - wefox-server
  wefox-server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: wefox-server
    ports:
      - '8000:8000'
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mongoose
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - wefox-mongo
    depends_on:
      - wefox-mongo
  wefox-mongo:
    image: mvertes/alpine-mongo
    container_name: wefox-mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
